// CourseData.js
const University_Logos = {
    Aws: '/Assets/University_Logos/Aws.svg',
    Duke_University: '/Assets/University_Logos/Duke_University.svg',
    Google: '/Assets/University_Logos/Google.svg',
    Harvard_University: '/Assets/University_Logos/Harvard_University.svg',
    IBM: '/Assets/University_Logos/IBM.svg',
    Meta: '/Assets/University_Logos/Meta.svg',
    MIT: '/Assets/University_Logos/Mit.svg',
    Stanford_University: '/Assets/University_Logos/Stanford_University.svg',
    University_of_Cambridge: '/Assets/University_Logos/University_of_Cambridge.svg',
    University_of_Michigan: '/Assets/University_Logos/University_of_Michigan.svg',
    University_of_Oxford: '/Assets/University_Logos/University_of_Oxford.svg',
    University_of_Pennsylvania: '/Assets/University_Logos/University_of_Pennsylvania.svg',
};

const courses = [
    {
        id: 1,
        title: "Google Data Analytics",
        imgSrc: "/Assets/Course/course1.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Data Analysis, Google Analytics, Data Visualization",
        rating: "5.0",
        reviews: "(10K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 2,
        title: "IBM Data Science",
        imgSrc: "/Assets/Course/course2.jpg",
        logo: University_Logos.IBM,
        universities: "IBM",
        skills: "Python, Machine Learning, Data Visualization",
        rating: "4.7",
        reviews: "(8K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
      },
      {
        id: 3,
        title: "AWS Solutions Architect",
        imgSrc: "/Assets/Course/course3.jpg",
        logo: University_Logos.Aws,
        universities: "Aws",
        skills: "Cloud Computing, AWS, Architecture Design",
        rating: "4.9",
        reviews: "(12K reviews)",
        subject: "Cloud Computing",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
      },
      {
        id: 4,
        title: "Meta Front-End Development",
        imgSrc: "/Assets/Course/course4.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "HTML, CSS, JavaScript, React",
        rating: "4.6",
        reviews: "(6K reviews)",
        subject: "Web Development",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
      },
      {
        id: 5,
        title: "AI Fundamentals",
        imgSrc: "/Assets/Course/course5.jpg",
        logo: University_Logos.Duke_University,
        universities: "Duke University",
        skills: "Artificial Intelligence, Python, Machine Learning",
        rating: "4.5",
        reviews: "(9K reviews)",
        subject: "Artificial Intelligence",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 6,
        title: "Stanford Machine Learning",
        imgSrc: "/Assets/Course/course6.jpg",
        logo: University_Logos.Stanford_University,
        universities: "Stanford University",
        skills: "Machine Learning, Python, Data Analysis",
        rating: "4.9",
        reviews: "(11K reviews)",
        subject: "Machine Learning",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 7,
        title: "Cambridge Data Science",
        imgSrc: "/Assets/Course/course7.jpg",
        logo: University_Logos.University_of_Cambridge,
        universities: "University of Cambridge",
        skills: "Data Science, Statistics, R Programming",
        rating: "4.8",
        reviews: "(7K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
      },
      {
        id: 8,
        title: "Oxford Cyber Security",
        imgSrc: "/Assets/Course/course8.jpg",
        logo: University_Logos.University_of_Oxford,
        universities: "University of Oxford",
        skills: "Cybersecurity, Ethical Hacking, Network Security",
        rating: "4.7",
        reviews: "(5K reviews)",
        subject: "Cybersecurity",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
      },
      {
        id: 9,
        title: "Harvard Business Analytics",
        imgSrc: "/Assets/Course/course9.jpg",
        logo: University_Logos.Harvard_University,
        universities: "Harvard University",
        skills: "Business Analytics, Data Visualization, Excel",
        rating: "4.8",
        reviews: "(9K reviews)",
        subject: "Business Analytics",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 10,
        title: "MIT Blockchain Technology",
        imgSrc: "/Assets/Course/course10.jpg",
        logo: University_Logos.MIT,
        universities: "MIT",
        skills: "Blockchain, Cryptography, Decentralization",
        rating: "4.9",
        reviews: "(7K reviews)",
        subject: "Blockchain",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
      },
      {
        id: 11,
        title: "AR/VR Development",
        imgSrc: "/Assets/Course/course11.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "Augmented Reality, Virtual Reality, Unity",
        rating: "4.6",
        reviews: "(4K reviews)",
        subject: "AR/VR Development",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
      },
      {
        id: 12,
        title: "Quantum Computing",
        imgSrc: "/Assets/Course/course12.jpg",
        logo: University_Logos.IBM,
        universities: "IBM",
        skills: "Quantum Computing, Qiskit, Python",
        rating: "4.7",
        reviews: "(5K reviews)",
        subject: "Quantum Computing",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 13,
        title: "Leadership and Management",
        imgSrc: "/Assets/Course/course13.jpg",
        logo: University_Logos.Harvard_University,
        universities: "Harvard University",
        skills: "Leadership, Decision-Making, Communication",
        rating: "4.8",
        reviews: "(6K reviews)",
        subject: "Leadership",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
      },
      {
        id: 14,
        title: "Mobile App Development",
        imgSrc: "/Assets/Course/course14.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Android Development, Kotlin, Java",
        rating: "4.7",
        reviews: "(8K reviews)",
        subject: "Mobile Development",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 15,
        title: "AI Ethics",
        imgSrc: "/Assets/Course/course15.jpg",
        logo: University_Logos.Stanford_University,
        universities: "Stanford University",
        skills: "Ethics, Artificial Intelligence, Policy",
        rating: "4.9",
        reviews: "(7K reviews)",
        subject: "AI Ethics",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
      },
      {
        id: 16,
        title: "Google Cloud ML",
        imgSrc: "/Assets/Course/course16.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Machine Learning, Google Cloud, Python",
        rating: "4.7",
        reviews: "(8K reviews)",
        subject: "Machine Learning",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 17,
        title: "IBM Blockchain Essentials",
        imgSrc: "/Assets/Course/course17.jpg",
        logo: University_Logos.IBM,
        universities: "IBM",
        skills: "Blockchain, Hyperledger, Smart Contracts",
        rating: "4.6",
        reviews: "(6K reviews)",
        subject: "Blockchain",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
      },
      {
        id: 18,
        title: "Meta AR/VR Development",
        imgSrc: "/Assets/Course/course18.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "Augmented Reality, Virtual Reality, Unity",
        rating: "4.9",
        reviews: "(9.5K reviews)",
        subject: "AR/VR Development",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 19,
        title: "Financial Engineering",
        imgSrc: "/Assets/Course/course19.jpg",
        logo: University_Logos.Duke_University,
        universities: "Duke University",
        skills: "Financial Engineering, Risk Management, MATLAB",
        rating: "4.8",
        reviews: "(7K reviews)",
        subject: "Financial Engineering",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
      },
      {
        id: 20,
        title: "Stanford Deep Learning",
        imgSrc: "/Assets/Course/course20.jpg",
        logo: University_Logos.Stanford_University,
        universities: "Stanford University",
        skills: "Deep Learning, TensorFlow, Neural Networks",
        rating: "4.9",
        reviews: "(11.5K reviews)",
        subject: "Deep Learning",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 21,
        title: "Advanced Data Analysis",
        imgSrc: "/Assets/Course/course21.jpg",
        logo: University_Logos.University_of_Cambridge,
        universities: "University of Cambridge",
        skills: "Advanced Data Analysis, R, Python",
        rating: "4.7",
        reviews: "(8.5K reviews)",
        subject: "Data Analysis",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 22,
        title: "Oxford Fintech",
        imgSrc: "/Assets/Course/course22.jpg",
        logo: University_Logos.University_of_Oxford,
        universities: "University of Oxford",
        skills: "Fintech, Cryptocurrency, Blockchain",
        rating: "4.8",
        reviews: "(7K reviews)",
        subject: "Fintech",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
      },
      {
        id: 23,
        title: "Google Mobile Dev",
        imgSrc: "/Assets/Course/course23.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Android Development, Kotlin, Java",
        rating: "4.6",
        reviews: "(5.5K reviews)",
        subject: "Mobile Development",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 24,
        title: "IBM Artificial Intelligence",
        imgSrc: "/Assets/Course/course24.jpg",
        logo: University_Logos.IBM,
        universities: "IBM",
        skills: "Artificial Intelligence, Machine Learning, Python",
        rating: "4.9",
        reviews: "(11K reviews)",
        subject: "Artificial Intelligence",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
      },
      {
        id: 25,
        title: "Meta Advanced JavaScript",
        imgSrc: "/Assets/Course/course25.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "JavaScript, Node.js, Web Development",
        rating: "4.7",
        reviews: "(7.5K reviews)",
        subject: "Web Development",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
      },
      {
        id: 26,
        title: "AWS DevOps Engineer",
        imgSrc: "/Assets/Course/course26.jpg",
        logo: University_Logos.Aws,
        universities: "Aws",
        skills: "DevOps, AWS, CI/CD",
        rating: "4.9",
        reviews: "(9.8K reviews)",
        subject: "DevOps",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 27,
        title: "Stanford Cybersecurity",
        imgSrc: "/Assets/Course/course27.jpg",
        logo: University_Logos.Stanford_University,
        universities: "Stanford University",
        skills: "Cybersecurity, Ethical Hacking, Python",
        rating: "4.8",
        reviews: "(7K reviews)",
        subject: "Cybersecurity",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
      },
      {
        id: 28,
        title: "Cambridge AI Ethics",
        imgSrc: "/Assets/Course/course28.jpg",
        logo: University_Logos.University_of_Cambridge,
        universities: "University of Cambridge",
        skills: "AI Ethics, Machine Learning, Policy",
        rating: "4.7",
        reviews: "(6.5K reviews)",
        subject: "AI Ethics",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
      },
      {
        id: 29,
        title: "Oxford Leadership Program",
        imgSrc: "/Assets/Course/course29.jpg",
        logo: University_Logos.University_of_Oxford,
        universities: "University of Oxford",
        skills: "Leadership, Management, Strategy",
        rating: "4.6",
        reviews: "(8K reviews)",
        subject: "Leadership",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
      },
      {
        id: 30,
        title: "Google Cloud Solutions",
        imgSrc: "/Assets/Course/course30.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Google Cloud, Cloud Solutions, DevOps",
        rating: "4.9",
        reviews: "(9K reviews)",
        subject: "Cloud Solutions",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
      },
      {
        id: 31,
        title: "Data Science with Python",
        imgSrc: "/Assets/Course/course9.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Python, Data Analysis, Data Visualization",
        rating: "4.8",
        reviews: "(8K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 32,
        title: "Introduction to AI",
        imgSrc: "/Assets/Course/course8.jpg",
        logo: University_Logos.Duke_University,
        universities: "Duke University",
        skills: "AI Fundamentals, Python, Ethics",
        rating: "4.7",
        reviews: "(6.5K reviews)",
        subject: "Artificial Intelligence",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 33,
        title: "Full-Stack Web Development",
        imgSrc: "/Assets/Course/course7.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "HTML, CSS, JavaScript, Node.js",
        rating: "4.6",
        reviews: "(9K reviews)",
        subject: "Web Development",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 34,
        title: "Data Visualization with Tableau",
        imgSrc: "/Assets/Course/course6.jpg",
        logo: University_Logos.University_of_Cambridge,
        universities: "University of Cambridge",
        skills: "Tableau, Data Visualization, Data Analysis",
        rating: "4.8",
        reviews: "(7K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 35,
        title: "Advanced JavaScript Concepts",
        imgSrc: "/Assets/Course/course5.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "JavaScript, ES6, Asynchronous Programming",
        rating: "4.7",
        reviews: "(8K reviews)",
        subject: "Web Development",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    },
    {
        id: 36,
        title: "Cybersecurity Fundamentals",
        imgSrc: "/Assets/Course/course4.jpg",
        logo: University_Logos.University_of_Oxford,
        universities: "University of Oxford",
        skills: "Network Security, Ethical Hacking, Risk Management",
        rating: "4.9",
        reviews: "(10K reviews)",
        subject: "Cybersecurity",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 37,
        title: "Deep Learning with TensorFlow",
        imgSrc: "/Assets/Course/course3.jpg",
        logo: University_Logos.Stanford_University,
        universities: "Stanford University",
        skills: "Deep Learning, TensorFlow, Neural Networks",
        rating: "4.8",
        reviews: "(11K reviews)",
        subject: "Machine Learning",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 38,
        title: "Robotics Process Automation",
        imgSrc: "/Assets/Course/course2.jpg",
        logo: University_Logos.IBM,
        universities: "IBM",
        skills: "RPA, Automation, Business Process",
        rating: "4.6",
        reviews: "(7.5K reviews)",
        subject: "Automation",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 39,
        title: "Natural Language Processing",
        imgSrc: "/Assets/Course/course1.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "NLP, Python, Machine Learning",
        rating: "4.8",
        reviews: "(8.5K reviews)",
        subject: "AI and ML",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 40,
        title: "DevOps Fundamentals",
        imgSrc: "/Assets/Course/course30.jpg",
        logo: University_Logos.Aws,
        universities: "Aws",
        skills: "DevOps, CI/CD, AWS",
        rating: "4.9",
        reviews: "(9K reviews)",
        subject: "DevOps",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 41,
        title: "Financial Data Analysis",
        imgSrc: "/Assets/Course/course29.jpg",
        logo: University_Logos.Harvard_University,
        universities: "Harvard University",
        skills: "Finance, Data Analysis, Excel",
        rating: "4.7",
        reviews: "(6K reviews)",
        subject: "Finance",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 42,
        title: "Advanced Python Programming",
        imgSrc: "/Assets/Course/course28.jpg",
        logo: University_Logos.MIT,
        universities: "MIT",
        skills: "Python, OOP, Data Structures",
        rating: "4.8",
        reviews: "(8K reviews)",
        subject: "Programming",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    },
    {
        id: 43,
        title: "Building Scalable Web Apps",
        imgSrc: "/Assets/Course/course27.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Node.js, Express, MongoDB",
        rating: "4.9",
        reviews: "(7K reviews)",
        subject: "Web Development",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 44,
        title: "Introduction to Cloud Computing",
        imgSrc: "/Assets/Course/course26.jpg",
        logo: University_Logos.Aws,
        universities: "Aws",
        skills: "Cloud Computing, AWS, Azure",
        rating: "4.7",
        reviews: "(5.5K reviews)",
        subject: "Cloud Computing",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 45,
        title: "Blockchain Basics",
        imgSrc: "/Assets/Course/course25.jpg",
        logo: University_Logos.MIT,
        universities: "MIT",
        skills: "Blockchain, Smart Contracts, Cryptography",
        rating: "4.8",
        reviews: "(8K reviews)",
        subject: "Blockchain",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    },
    {
        id: 46,
        title: "Ethical Hacking Bootcamp",
        imgSrc: "/Assets/Course/course24.jpg",
        logo: University_Logos.University_of_Oxford,
        universities: "University of Oxford",
        skills: "Ethical Hacking, Penetration Testing, Security",
        rating: "4.9",
        reviews: "(9K reviews)",
        subject: "Cybersecurity",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 47,
        title: "Data Science for Business",
        imgSrc: "/Assets/Course/course23.jpg",
        logo: University_Logos.Harvard_University,
        universities: "Harvard University",
        skills: "Business Analytics, Data Science, Strategy",
        rating: "4.7",
        reviews: "(6.5K reviews)",
        subject: "Business Analytics",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 48,
        title: "Machine Learning for Finance",
        imgSrc: "/Assets/Course/course22.jpg",
        logo: University_Logos.IBM,
        universities: "IBM",
        skills: "Machine Learning, Finance, Data Analysis",
        rating: "4.8",
        reviews: "(7K reviews)",
        subject: "Finance",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 49,
        title: "Web Accessibility Essentials",
        imgSrc: "/Assets/Course/course21.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "Web Accessibility, UX, Design Principles",
        rating: "4.6",
        reviews: "(5.5K reviews)",
        subject: "Web Development",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    },
    {
        id: 50,
        title: "Introduction to Data Science",
        imgSrc: "/Assets/Course/course20.jpg",
        logo: University_Logos.University_of_Cambridge,
        universities: "University of Cambridge",
        skills: "Data Science, R, Data Analysis",
        rating: "4.9",
        reviews: "(10K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 51,
        title: "Cloud Architecture Basics",
        imgSrc: "/Assets/Course/course19.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Cloud Architecture, AWS, GCP",
        rating: "4.6",
        reviews: "(4K reviews)",
        subject: "Cloud Computing",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 52,
        title: "Fundamentals of Data Science",
        imgSrc: "/Assets/Course/course18.jpg",
        logo: University_Logos.MIT,
        universities: "MIT",
        skills: "Data Science, Statistics, Python",
        rating: "4.7",
        reviews: "(5K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 53,
        title: "Introduction to Quantum Computing",
        imgSrc: "/Assets/Course/course17.jpg",
        logo: University_Logos.Stanford_University,
        universities: "Stanford University",
        skills: "Quantum Computing, Qubits, Algorithms",
        rating: "4.8",
        reviews: "(2K reviews)",
        subject: "Quantum Computing",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 54,
        title: "Full-Stack Development with MERN",
        imgSrc: "/Assets/Course/course16.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "MongoDB, Express, React, Node.js",
        rating: "4.6",
        reviews: "(6.5K reviews)",
        subject: "Web Development",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 55,
        title: "Ethics in AI",
        imgSrc: "/Assets/Course/course15.jpg",
        logo: University_Logos.Duke_University,
        universities: "Duke University",
        skills: "AI Ethics, Data Privacy, Policy",
        rating: "4.7",
        reviews: "(3K reviews)",
        subject: "AI Ethics",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    },
    {
        id: 56,
        title: "Data Mining Techniques",
        imgSrc: "/Assets/Course/course14.jpg",
        logo: University_Logos.University_of_Cambridge,
        universities: "University of Cambridge",
        skills: "Data Mining, R, SQL",
        rating: "4.8",
        reviews: "(4.5K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 57,
        title: "Game Development with Unity",
        imgSrc: "/Assets/Course/course13.jpg",
        logo: University_Logos.University_of_Oxford,
        universities: "University of Oxford",
        skills: "Unity, C#, Game Design",
        rating: "4.9",
        reviews: "(7K reviews)",
        subject: "Game Development",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 58,
        title: "Web Development Bootcamp",
        imgSrc: "/Assets/Course/course12.jpg",
        logo: University_Logos.Harvard_University,
        universities: "Harvard University",
        skills: "HTML, CSS, JavaScript, React",
        rating: "4.7",
        reviews: "(10K reviews)",
        subject: "Web Development",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 59,
        title: "Artificial Intelligence for Beginners",
        imgSrc: "/Assets/Course/course11.jpg",
        logo: University_Logos.Aws,
        universities: "Aws",
        skills: "AI Basics, Python, Machine Learning",
        rating: "4.5",
        reviews: "(5K reviews)",
        subject: "Artificial Intelligence",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 60,
        title: "Data Analytics for Business",
        imgSrc: "/Assets/Course/course10.jpg",
        logo: University_Logos.IBM,
        universities: "IBM",
        skills: "Business Analytics, Excel, Tableau",
        rating: "4.7",
        reviews: "(6K reviews)",
        subject: "Business Analytics",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 61,
        title: "Introduction to Blockchain Technology",
        imgSrc: "/Assets/Course/course9.jpg",
        logo: University_Logos.MIT,
        universities: "MIT",
        skills: "Blockchain, Cryptography, Smart Contracts",
        rating: "4.6",
        reviews: "(4.5K reviews)",
        subject: "Blockchain",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 62,
        title: "Data Science with R",
        imgSrc: "/Assets/Course/course8.jpg",
        logo: University_Logos.University_of_Cambridge,
        universities: "University of Cambridge",
        skills: "R, Data Analysis, Visualization",
        rating: "4.8",
        reviews: "(3K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 63,
        title: "Machine Learning with R",
        imgSrc: "/Assets/Course/course7.jpg",
        logo: University_Logos.Stanford_University,
        universities: "Stanford University",
        skills: "R, Machine Learning, Data Analysis",
        rating: "4.9",
        reviews: "(5K reviews)",
        subject: "Machine Learning",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 64,
        title: "Digital Marketing Strategies",
        imgSrc: "/Assets/Course/course6.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "Digital Marketing, SEO, Analytics",
        rating: "4.7",
        reviews: "(4.5K reviews)",
        subject: "Marketing",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 65,
        title: "Introduction to Mobile Development",
        imgSrc: "/Assets/Course/course5.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Android, iOS, React Native",
        rating: "4.6",
        reviews: "(3K reviews)",
        subject: "Mobile Development",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 66,
        title: "Cybersecurity Risk Management",
        imgSrc: "/Assets/Course/course4.jpg",
        logo: University_Logos.University_of_Oxford,
        universities: "University of Oxford",
        skills: "Risk Management, Compliance, Security",
        rating: "4.8",
        reviews: "(6K reviews)",
        subject: "Cybersecurity",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 67,
        title: "Data Visualization with Python",
        imgSrc: "/Assets/Course/course3.jpg",
        logo: University_Logos.MIT,
        universities: "MIT",
        skills: "Python, Data Visualization, Matplotlib",
        rating: "4.7",
        reviews: "(5K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 68,
        title: "Foundations of DevOps",
        imgSrc: "/Assets/Course/course2.jpg",
        logo: University_Logos.Aws,
        universities: "Aws",
        skills: "DevOps, CI/CD, Cloud Services",
        rating: "4.8",
        reviews: "(7K reviews)",
        subject: "DevOps",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 69,
        title: "Data-Driven Decision Making",
        imgSrc: "/Assets/Course/course2.jpg",
        logo: University_Logos.Harvard_University,
        universities: "Harvard University",
        skills: "Data Analysis, Business Strategy, Excel",
        rating: "4.6",
        reviews: "(3K reviews)",
        subject: "Business Analytics",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    },
    {
        id: 70,
        title: "Introduction to AI Programming",
        imgSrc: "/Assets/Course/course1.jpg",
        logo: University_Logos.Duke_University,
        universities: "Duke University",
        skills: "AI Programming, Python, TensorFlow",
        rating: "4.7",
        reviews: "(2.5K reviews)",
        subject: "Artificial Intelligence",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 71,
        title: "Advanced Cloud Solutions",
        imgSrc: "/Assets/Course/course30.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Cloud Solutions, AWS, Azure",
        rating: "4.8",
        reviews: "(4K reviews)",
        subject: "Cloud Computing",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 72,
        title: "Introduction to Robotics",
        imgSrc: "/Assets/Course/course29.jpg",
        logo: University_Logos.IBM,
        universities: "IBM",
        skills: "Robotics, Programming, Automation",
        rating: "4.6",
        reviews: "(3K reviews)",
        subject: "Robotics",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 73,
        title: "Understanding Neural Networks",
        imgSrc: "/Assets/Course/course28.jpg",
        logo: University_Logos.Stanford_University,
        universities: "Stanford University",
        skills: "Neural Networks, Deep Learning, TensorFlow",
        rating: "4.9",
        reviews: "(5K reviews)",
        subject: "Machine Learning",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 74,
        title: "Social Media Marketing",
        imgSrc: "/Assets/Course/course27.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "Social Media, Marketing Strategies, Analytics",
        rating: "4.7",
        reviews: "(4K reviews)",
        subject: "Marketing",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    },
    {
        id: 75,
        title: "Introduction to Computer Vision",
        imgSrc: "/Assets/Course/course26.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Computer Vision, OpenCV, Machine Learning",
        rating: "4.8",
        reviews: "(3K reviews)",
        subject: "Computer Vision",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 76,
        title: "Data Privacy and Security",
        imgSrc: "/Assets/Course/course25.jpg",
        logo: University_Logos.University_of_Oxford,
        universities: "University of Oxford",
        skills: "Data Privacy, Compliance, Security",
        rating: "4.9",
        reviews: "(5K reviews)",
        subject: "Cybersecurity",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 77,
        title: "Intro to Software Engineering",
        imgSrc: "/Assets/Course/course24.jpg",
        logo: University_Logos.Harvard_University,
        universities: "Harvard University",
        skills: "Software Engineering, Agile, Development",
        rating: "4.6",
        reviews: "(4K reviews)",
        subject: "Software Engineering",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 78,
        title: "Advanced Data Analysis with Python",
        imgSrc: "/Assets/Course/course23.jpg",
        logo: University_Logos.MIT,
        universities: "MIT",
        skills: "Data Analysis, Python, Pandas",
        rating: "4.8",
        reviews: "(5K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 79,
        title: "Financial Technologies Overview",
        imgSrc: "/Assets/Course/course22.jpg",
        logo: University_Logos.IBM,
        universities: "IBM",
        skills: "Fintech, Blockchain, Data Analysis",
        rating: "4.7",
        reviews: "(4K reviews)",
        subject: "Finance",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 80,
        title: "Digital Product Management",
        imgSrc: "/Assets/Course/course21.jpg",
        logo: University_Logos.Aws,
        universities: "Aws",
        skills: "Product Management, Agile, Development",
        rating: "4.6",
        reviews: "(3K reviews)",
        subject: "Product Management",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 81,
        title: "Web Performance Optimization",
        imgSrc: "/Assets/Course/course20.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "Web Performance, Optimization, Analytics",
        rating: "4.7",
        reviews: "(4K reviews)",
        subject: "Web Development",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    },
    {
        id: 82,
        title: "Artificial Intelligence in Healthcare",
        imgSrc: "/Assets/Course/course19.jpg",
        logo: University_Logos.Duke_University,
        universities: "Duke University",
        skills: "AI in Healthcare, Data Analysis, Ethics",
        rating: "4.8",
        reviews: "(3K reviews)",
        subject: "AI Ethics",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 83,
        title: "Introduction to AR/VR Development",
        imgSrc: "/Assets/Course/course18.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "AR, VR, Game Development",
        rating: "4.6",
        reviews: "(2.5K reviews)",
        subject: "AR/VR Development",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 84,
        title: "Developing RESTful APIs with Node.js",
        imgSrc: "/Assets/Course/course17.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "Node.js, RESTful APIs, Express",
        rating: "4.7",
        reviews: "(4K reviews)",
        subject: "Web Development",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    },
    {
        id: 85,
        title: "Data Governance and Compliance",
        imgSrc: "/Assets/Course/course6.jpg",
        logo: University_Logos.University_of_Oxford,
        universities: "University of Oxford",
        skills: "Data Governance, Compliance, Privacy",
        rating: "4.8",
        reviews: "(5K reviews)",
        subject: "Data Management",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 86,
        title: "Introduction to Game Design",
        imgSrc: "/Assets/Course/course15.jpg",
        logo: University_Logos.MIT,
        universities: "MIT",
        skills: "Game Design, Unity, C#",
        rating: "4.9",
        reviews: "(6K reviews)",
        subject: "Game Development",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 87,
        title: "Cybersecurity Threats and Defense",
        imgSrc: "/Assets/Course/course14.jpg",
        logo: University_Logos.Harvard_University,
        universities: "Harvard University",
        skills: "Threat Detection, Defense Strategies",
        rating: "4.8",
        reviews: "(4.5K reviews)",
        subject: "Cybersecurity",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 88,
        title: "Machine Learning in Python",
        imgSrc: "/Assets/Course/course13.jpg",
        logo: University_Logos.Aws,
        universities: "Aws",
        skills: "Python, Machine Learning, Data Science",
        rating: "4.7",
        reviews: "(5K reviews)",
        subject: "Machine Learning",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 89,
        title: "Effective Data Storytelling",
        imgSrc: "/Assets/Course/course12.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Data Visualization, Storytelling, Presentation",
        rating: "4.6",
        reviews: "(3K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    },
    {
        id: 90,
        title: "Introduction to Internet of Things (IoT)",
        imgSrc: "/Assets/Course/course11.jpg",
        logo: University_Logos.IBM,
        universities: "IBM",
        skills: "IoT, Sensors, Data Collection",
        rating: "4.7",
        reviews: "(4K reviews)",
        subject: "IoT",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 91,
        title: "Data Analysis with SQL",
        imgSrc: "/Assets/Course/course10.jpg",
        logo: University_Logos.University_of_Cambridge,
        universities: "University of Cambridge",
        skills: "SQL, Data Analysis, Databases",
        rating: "4.8",
        reviews: "(3.5K reviews)",
        subject: "Data Science",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 92,
        title: "Fundamentals of Web Accessibility",
        imgSrc: "/Assets/Course/course9.jpg",
        logo: University_Logos.Harvard_University,
        universities: "Harvard University",
        skills: "Web Accessibility, UX Design, Compliance",
        rating: "4.6",
        reviews: "(4K reviews)",
        subject: "Web Development",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    },
    {
        id: 93,
        title: "Digital Forensics and Cybersecurity",
        imgSrc: "/Assets/Course/course8.jpg",
        logo: University_Logos.Duke_University,
        universities: "Duke University",
        skills: "Digital Forensics, Cybersecurity, Investigation",
        rating: "4.7",
        reviews: "(2K reviews)",
        subject: "Cybersecurity",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 94,
        title: "Mobile Application Development",
        imgSrc: "/Assets/Course/course7.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "Android, iOS, App Development",
        rating: "4.8",
        reviews: "(3.5K reviews)",
        subject: "Mobile Development",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 95,
        title: "AI-Powered Chatbots",
        imgSrc: "/Assets/Course/course6.jpg",
        logo: University_Logos.Aws,
        universities: "Aws",
        skills: "Chatbots, AI, Python",
        rating: "4.6",
        reviews: "(3K reviews)",
        subject: "Artificial Intelligence",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 96,
        title: "Natural Language Processing (NLP)",
        imgSrc: "/Assets/Course/course5.jpg",
        logo: University_Logos.Meta,
        universities: "Meta",
        skills: "NLP, Python, AI",
        rating: "4.7",
        reviews: "(4K reviews)",
        subject: "Machine Learning",
        language: "English",
        product: "Courses",
        duration: "6-12 months",
    },
    {
        id: 97,
        title: "Data Warehousing and ETL",
        imgSrc: "/Assets/Course/course4.jpg",
        logo: University_Logos.IBM,
        universities: "IBM",
        skills: "ETL, Data Warehousing, SQL",
        rating: "4.6",
        reviews: "(2.5K reviews)",
        subject: "Data Management",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 98,
        title: "Introduction to Ethical Hacking",
        imgSrc: "/Assets/Course/course3.jpg",
        logo: University_Logos.University_of_Oxford,
        universities: "University of Oxford",
        skills: "Ethical Hacking, Security Testing",
        rating: "4.9",
        reviews: "(3K reviews)",
        subject: "Cybersecurity",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 99,
        title: "Augmented Reality for Beginners",
        imgSrc: "/Assets/Course/course2.jpg",
        logo: University_Logos.Google,
        universities: "Google",
        skills: "AR Development, Unity, Design",
        rating: "4.6",
        reviews: "(2K reviews)",
        subject: "AR/VR Development",
        language: "English",
        product: "Courses",
        duration: "3-6 months",
    },
    {
        id: 100,
        title: "Introduction to SaaS Products",
        imgSrc: "/Assets/Course/course1.jpg",
        logo: University_Logos.Aws,
        universities: "Aws",
        skills: "SaaS, Cloud Computing, Business Model",
        rating: "4.8",
        reviews: "(3.5K reviews)",
        subject: "Cloud Computing",
        language: "English",
        product: "Courses",
        duration: "1-3 months",
    }
];
export { courses};
